fix: Workaround breakage in Pygments 2.6
Since the 2.6.0 release, pipelines have failed with the error

File "/usr/local/lib/python2.7/dist-packages/Pygments-2.6.1-py2.7.egg/pygments/formatters/html.py", line 554
  file=sys.stderr)
         ^
 SyntaxError: invalid syntax

Since this is likely just a Python 2.7 compatibility issue, we restrict
the version specification for now.

Closes: LINOTP-1305